[package]
name = "noah"
version = "0.1.0"
edition = "2021"
description = "Critical Care Nurse AI Agent Toolkit with Flood EHR"
authors = ["Shane McCusker <smccusker22@gmail.com>"]
license = "MIT"
readme = "README.md"

[features]
default = ["sqlite", "http"]
full = ["sqlite", "http", "blockchain", "ui", "clickhouse"]
http = [
    "actix-web",
    "actix-cors",
    "redis",
    "bb8-redis",
    "serde_json",
    "serde",
    "uuid",
]
blockchain = ["sha2"]
sqlite = ["sqlx"]
ui = ["iced"]
clickhouse = ["clickhouse-rs"]

[dependencies]
tokio = { version = "1.43", features = ["full"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "chrono"], optional = true }
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
dotenv = "0.15"
sha2 = { version = "0.10", optional = true }
chrono = { version = "0.4", features = ["serde"] }
dashmap = "5.4"
tokio-retry = "0.3"
redis = { version = "0.23", features = ["tokio-comp"], optional = true }
bb8-redis = { version = "0.20", optional = true }
actix-web = { version = "4", features = ["rustls-0_23"], optional = true }
actix-cors = { version = "0.6", optional = true }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.12", features = ["serde", "v4"], optional = true }
ctor = "0.2"
metrics = "0.21"
metrics-exporter-prometheus = "0.12"
once_cell = "1.20"
thiserror = "2.0"
iced = { version = "0.12", optional = true }
pprof = "0.13"
async-trait = "0.1"
clickhouse-rs = { version = "1.0", optional = true }
lazy_static = "1.4.0"
hyper = { version = "0.14", features = ["full"] }
futures = "0.3"
rand = "0.8"

[dev-dependencies]
flamegraph = "0.6"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true