[package]
name = "noah"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite"] }
flexi_logger = "0.28"
prometheus = "0.13"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
hyper = { version = "0.14", features = ["server", "http1"] }
serde_json = "1"
dotenv = "0.15"
rig-core = "0.9.0"
rig-mock = { version = "0.9.0", optional = true }
rig-mongodb = { version = "0.9.0", optional = true }
rig-postgres = { version = "0.9.0", optional = true }
serde = { version = "1", features = ["derive"] }

[features]
default = ["sqlite"]
sqlite = ["sqlx"]
mongodb = ["rig-mongodb"]
postgres = ["rig-postgres"]
