[package]
name = "noah"
version = "0.1.0"
edition = "2021"
authors = ["Shane <shanemccusker@gmail.com>"]
description = "Noah - Next-generation AI-Powered Healthcare Platform"
repository = "https://github.com/shanesnotes/noah"
license = "Proprietary"
readme = "README.md"

# Optimize binary size and performance
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Group dependencies by purpose
[dependencies]
# Core web framework
actix-web = { version = "4.3.1", features = ["rustls"] }
actix-files = "0.6.2"
actix-rt = "2.8.0"
actix-cors = "0.6.4"
actix-web-actors = "4.2.0"

# WebSockets
tokio-tungstenite = "0.18.0"
tungstenite = "0.18.0"

# Async runtime
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread", "io-util", "time", "sync", "fs"] }
futures = "0.3.28"

# Serialization
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"

# Database
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "json", "uuid", "migrate", "offline"] }

# Configuration
config = { version = "0.13.3", features = ["toml"] }
dotenv = "0.15.0"

# Logging and diagnostics
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing-actix-web = "0.7.4"

# Error handling
thiserror = "1.0.40"
anyhow = "1.0.70"

# Security
jsonwebtoken = "8.3.0"
argon2 = "0.5.0"
rand = "0.8.5"
rustls = "0.21.1"
rustls-pemfile = "1.0.2"

# Healthcare specific
fhir-rs = { version = "0.4.0", optional = true }
dicom-rs = { version = "0.5.0", optional = true }

# Utilities
uuid = { version = "1.3.1", features = ["v4", "serde"] }
chrono = { version = "0.4.24", features = ["serde"] }
url = "2.3.1"
validator = { version = "0.16.0", features = ["derive"] }

# AI/ML capabilities
[dependencies.ai]
optional = true
package = "noah-ai"
version = "0.1.0"
path = "crates/noah-ai"

# Feature flags for optional components
[features]
default = ["security"]
security = []
fhir = ["fhir-rs"]
dicom = ["dicom-rs"]
ml = ["ai"]
telemetry = ["tracing/attributes"]
production = ["security", "telemetry"]

# Define the library
[lib]
name = "noah"
path = "src/lib.rs"

# Define the binary
[[bin]]
name = "noah"
path = "src/main.rs"

# Development dependencies
[dev-dependencies]
mockall = "0.11.4"
test-case = "3.1.0"
criterion = "0.4.0"
fake = { version = "2.5.0", features = ["derive", "chrono"] }
wiremock = "0.5.18"

# Benchmarking configuration
[[bench]]
name = "api_benchmarks"
harness = false
path = "benches/api_benchmarks.rs"

# Workspace configuration for multi-crate setup
[workspace]
members = [
    "crates/noah-ai",
    "crates/noah-cli"
]