version: "3.8"
services:
  noah:
    build: .
    ports:
      - "8081:8081"  # HTTP API
      - "9090:9090"  # Prometheus metrics
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - DB_TYPE=${DB_TYPE:-clickhouse}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./noah.db:/app/noah.db  # Optional SQLite persistence
    depends_on:
      websocket-server:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    command: ["--command", "launch-flood", "--mode", "nurse"]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  websocket-server:
    image: node:18
    working_dir: /app
    volumes:
      - ./websocket-server:/app
    command: ["npm", "start"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "ws://localhost:8080/vitals"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24  # Updated to latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_HOST=0.0.0.0
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"  # Avoid conflict with Noah's 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  redis-data:
  clickhouse-data:
  clickhouse-logs: