global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "noah"
    static_configs:
      - targets: ["noah:9090"]  # Noah's metrics endpoint
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]